networks:
  vlad-yakovlev-dev:
    name: vlad-yakovlev-dev

services:
  mongo:
    image: mongo:5.0.17
    networks:
      - vlad-yakovlev-dev
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - $PWD/db:/data/db
    healthcheck:
      test: |
        test $$(mongo --quiet --eval "rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongo' }] }).ok || rs.status().ok") -eq 1
      interval: 10s
      start_period: 30s
    command: "--bind_ip_all --replSet rs0"
    restart: always

  mongo-backup:
    image: ghcr.io/tiredofit/docker-db-backup:3.9.0
    networks:
      - vlad-yakovlev-dev
    volumes:
      - $PWD/backups:/backups
    environment:
      CONTAINER_ENABLE_MONITORING: FALSE
      DB_TYPE: mongo
      DB_HOST: mongo
      DB_NAME: ALL
      DB_DUMP_TARGET: /backups
      # Backup every hour
      DB_DUMP_FREQ: 60
      # Cleanup backups older than 10 days
      DB_CLEANUP_TIME: 14400
    restart: always
