name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency: ci-${{ github.ref }}

jobs:
  deploy:
    if: github.repository == 'vlad-yakovlev/mongo' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean droplet
        uses: appleboy/ssh-action@master
        env:
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: SHA
          script_stop: true
          script: |
            cd Projects/mongo
            git fetch --prune --prune-tags --verbose
            git checkout $SHA
            docker compose up -d --build
