name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency: ci

jobs:
  deploy:
    needs: checks
    if: github.repository == 'vlad-yakovlev/mongo' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd Projects/mongo
            git pull
            docker compose up -d --build
